config/routes.rb
require 'api_constraints'

PassServer::Application.routes.draw do

  constraints(:subdomain => /^(|www)$/) do
    get '/signup' => 'users#new', as: 'signup'
    get '/login' => 'sessions#new', as: 'login'
    get '/logout' => 'sessions#destroy', as: 'logout'

    resources :users
    patch 'users/update_password/:id' => 'users#update_password', as: 'update_password'

    resources :sessions
    post 'sessions/callback' => 'sessions#callback', as: 'callback'

    resources :devices
    get 'devices/logins/:id' => 'devices#logins', as: 'logins'

    resources :device_accounts

    get 'about' => 'about#index'
    
    get 'developers' => 'developers#index'
    get 'developers/api' => 'developers#api', as: 'api'

    resources :services

    root to: 'devices#index'
  end

  constraints :subdomain => 'api' do
    scope module: :api do

      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        # Give them a blank page as the default route so it doesn't look like the API is down
        root to: proc { [200, {}, ['']] }

        post 'sessions' => 'sessions#create'
        get 'sessions' => 'sessions#get'
        get 'sessions/authenticate' => 'sessions#authenticate'
        post 'sessions/authenticate' => 'sessions#do_authentication'
        get 'sessions/:id' => 'sessions#get'

        post 'devices' => 'devices#create'
        post 'devices/register' => 'devices#register'

        post 'users' => 'users#create'
        get 'users' => 'users#get'
        delete 'users' => 'users#destroy'

        get '*a' => 'errors#routing'
        post '*a' => 'errors#routing'
        delete '*a' => 'errors#routing'
        patch '*a' => 'errors#routing'
        put '*a' => 'errors#routing'
      end
      
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#

class User < ActiveRecord::Base

	has_secure_password

	has_many :devices
  has_many :device_accounts, through: :devices
  has_many :developer_accounts

  validates_presence_of :password, :on => :create
  validates_presence_of :email
	validates_uniqueness_of :email
	validates :email, :format => { :with => /@/ }
	
end

app/controllers/api/v1/users_controller.rb
module Api
	module V1
		class UsersController < ApiController
			respond_to :json

			# == Create a user
			#
			# Required parameters:
			# => email
			# => password
			#
			# Returns:
			# => id
			# => email
			# => created_at
			#

			def create
				params.required(:email)
				params.required(:password)

				@user = User.create(:email => params[:email], :password => params[:password])

				invalid_request_error_check
			end

			# == Get a user
			#
			# Required parameters:
			# => id
			#
			# Returns:
			# => id
			# => email
			#

			def get
				params.required(:id)	

				# Grab the service that is trying to authenticate
        unathenticated_error unless @api_consumer.is_a? Service
        service = @api_consumer

				@user = service.users.find params[:id]
			end

			# == Destroy a user
			#
			# Required parameters:
			# => email
			# => password
			#
			# Returns nothing
			#

			def destroy
				params.required(:email)
        params.required(:password)

        # Authenticate the user
        begin
          user = User.find_by(email: params[:email])

          raise ActiveRecord::RecordNotFound unless user && user.authenticate(params[:password])
        rescue ActiveRecord::RecordNotFound
          return handle_error('Invalid email and password combination.', 'invalid_request_error', 401);
        end

        user.destroy

        render nothing: true
			end

			private

			# == Error check
			#
			# Check for active record errors. Set status header to 500 and display errors as JSON 
			# if any are found.
			#

			def api_error_check(record = @user)
				super record
			end

			def invalid_request_error_check(record = @user)
				super record
			end

		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render "new"
    end
  end

  def show
  end

  def update
    attributes = params.require(:user).permit(:email)
    current_user.update attributes

    render :show
  end

  def update_password
    attributes = params.require(:user).permit(:password, :password_confirmation)

    @current_password_error = "Current password is incorrect." unless authenticate(current_user.email, params[:user[:current_password]])
     
    current_user.update attributes

    render :show
  end

  private

  def user_params
    params.required(:user).permit(:email, :password, :password_confirmation)
  end

end

app/views/users/new.html.erb
<article>
  <div class="create-account">
    <h1>Create an Account</h1>
    <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>There were some problems creating your account.</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <%= form_for @user do |f| %>
      <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <%= submit_tag "Sign Up", class: "btn-signup" %>
    <% end %>
  </div>
</article>

app/views/users/show.html.erb
<h1>Account</h1>
<h2>Update</h2>
<%= form_for current_user, html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= label_tag :email, 'Email', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="form-actions">
    <input class="btn-submit" type="submit" value="Update" />
  </div>
<% end %>
<h2>Change your password</h2>
<%= form_for current_user, action: update_password_path(current_user), html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= label_tag :current_password, 'Current Password', class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :current_password %>
      <span class="error"><%= @current_password_error %></span>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :password, 'Password', class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="control-group">
    <%= label_tag :password_confirm, 'Confirm Password', class: 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirm %>
    </div>
  </div>
  <div class="form-actions">
    <input class="btn-submit" type="submit" value="Update" />
  </div>
<% end %>