config/routes.rb
require 'api_constraints'

PassServer::Application.routes.draw do

  constraints(:subdomain => /^(|www)$/) do
    get '/signup' => 'users#new', as: 'signup'
    get '/login' => 'sessions#new', as: 'login'
    get '/logout' => 'sessions#destroy', as: 'logout'

    resources :users
    patch 'users/update_password/:id' => 'users#update_password', as: 'update_password'

    resources :sessions
    post 'sessions/callback' => 'sessions#callback', as: 'callback'

    resources :devices
    get 'devices/logins/:id' => 'devices#logins', as: 'logins'

    resources :device_accounts

    get 'about' => 'about#index'
    
    get 'developers' => 'developers#index'
    get 'developers/api' => 'developers#api', as: 'api'

    resources :services

    root to: 'devices#index'
  end

  constraints :subdomain => 'api' do
    scope module: :api do

      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        # Give them a blank page as the default route so it doesn't look like the API is down
        root to: proc { [200, {}, ['']] }

        post 'sessions' => 'sessions#create'
        get 'sessions' => 'sessions#get'
        get 'sessions/authenticate' => 'sessions#authenticate'
        post 'sessions/authenticate' => 'sessions#do_authentication'
        get 'sessions/:id' => 'sessions#get'

        post 'devices' => 'devices#create'
        post 'devices/register' => 'devices#register'

        post 'users' => 'users#create'
        get 'users' => 'users#get'
        delete 'users' => 'users#destroy'

        get '*a' => 'errors#routing'
        post '*a' => 'errors#routing'
        delete '*a' => 'errors#routing'
        patch '*a' => 'errors#routing'
        put '*a' => 'errors#routing'
      end
      
    end
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
    
  end

end

app/views/about/index.html.erb
<h1>What is Pass?</h1>
<p>
  Pass is an experimental authentication system created in an attempt to provide an alternate to password-based credentials.
</p>
<h1>How does it work?</h1>
<p>
  Authenticaiton with Pass is a simple as scanning a QR code with your smartphone and you're logged in.
</p>
<h1>No really, how does it work?</h1>
<p>
  A mix of WebSockets, a Rails REST API, an iOS application, and Node.js are used to orchstrate the whole process. Take a look at the source if you're interested. The Node and Rails server can be found <%= link_to 'here', 'https://github.com/jamespbrennan' %>, a Ruby API <%= link_to 'here', 'https://github.com/jamespbrennan' %>, and the iOS application <%= link_to 'here', 'https://github.com/jamespbrennan' %>.
</p>
<h1>Is it secure?</h1>
<p>
  Pass uses secure one-time-use tokens and strong elliptic curve cryptography. The <%= link_to 'Curve25519 algorithm', 'http://cr.yp.to/ecdh.html' %> is used for it's speed and security to create signatures and authenticate you to the centralized authentication server. 
</p>
<h1>Cool, how do I use it?</h1>
<p>
  There is currenly only a client available for iOS devices. Simply download the application and create an account.
</p>
<p><%= link_to 'Download the App', 'http://apple.com', class: 'btn' %></p>
<p>
  <%= link_to 'Developers', developers_url %> can easily integrate Pass into their sites to enable users to login via Pass.
</p>
<p><%= link_to 'Checkout the API', developers_url, class: 'btn' %></p>
<h1>Who made this?</h1>
<p>
  Pass was created by web developer <%= link_to 'James Brennan', 'http://www.jamesbrennan.ca' %>. James is currently seeking full time employment, so <%= link_to 'drop him a line', 'mailto:james@jamesbrennan.ca' %> if you're interested in hiring him.
</p>