config/routes.rb
require 'api_constraints'

PassServer::Application.routes.draw do

  constraints(:subdomain => /^(|www)$/) do
    get '/signup' => 'users#new', as: 'signup'
    get '/login' => 'sessions#new', as: 'login'
    get '/logout' => 'sessions#destroy', as: 'logout'

    resources :users
    patch 'users/update_password/:id' => 'users#update_password', as: 'update_password'

    resources :sessions
    post 'sessions/callback' => 'sessions#callback', as: 'callback'

    resources :devices
    get 'devices/logins/:id' => 'devices#logins', as: 'logins'

    resources :device_accounts

    get 'about' => 'about#index'
    
    get 'developers' => 'developers#index'
    get 'developers/api' => 'developers#api', as: 'api'

    resources :services

    root to: 'devices#index'
  end

  constraints :subdomain => 'api' do
    scope module: :api do

      scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        # Give them a blank page as the default route so it doesn't look like the API is down
        root to: proc { [200, {}, ['']] }

        post 'sessions' => 'sessions#create'
        get 'sessions' => 'sessions#get'
        get 'sessions/authenticate' => 'sessions#authenticate'
        post 'sessions/authenticate' => 'sessions#do_authentication'
        get 'sessions/:id' => 'sessions#get'

        post 'devices' => 'devices#create'
        post 'devices/register' => 'devices#register'

        post 'users' => 'users#create'
        get 'users' => 'users#get'
        delete 'users' => 'users#destroy'

        get '*a' => 'errors#routing'
        post '*a' => 'errors#routing'
        delete '*a' => 'errors#routing'
        patch '*a' => 'errors#routing'
        put '*a' => 'errors#routing'
      end
      
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pass</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Pass</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <% if current_user %>
              <li>
                <a href="/">Devices</a>
              </li>
              <% end %>
            </ul>
            <ul class="nav pull-right">
              <% if current_user %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Log Out", logout_path %></li>
                  <li><%= link_to "Account", user_path(current_user) %></li>
                </ul>
              </li>
              <% else %>
              <li>
                <%= link_to "Sign Up", signup_path %>
              </li>
              <li>
                <%= link_to "Log In", login_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert-#{name}" %>
    <% end %>

    <%= yield %>
    </div>
    <div id="push"></div>
  </div>
  <footer>
    <ul>
      <li><%= link_to 'Developers', developers_path %></li>
      <li><a href="mailto:support@passauth.net">Contact</a></li>
      <li><%= link_to 'About', about_path %></li>
      <li>&copy; 2013 Pass Auth</li>
    </ul>
  </footer>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-28924535-2', 'passauth.net');
    ga('send', 'pageview');

  </script>
</body>
</html>

app/views/layouts/developers.html.erb
<% content_for :content do %>
  <ul class="nav nav-tabs">
    <li>About</li>
    <li>API</li>
  </ul>
<% end %>
<%= render template: 'layouts/application' %>